### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by JigaoLuo** [jk50505k/wenku_spider#1]
```
1  jigao  ~/workspace/wenku_spider  
> python 百度文库.py 
  File "百度文库.py", line 111
    print(text,end='')
                  ^
SyntaxError: invalid syntax
 1  jigao  ~/workspace/wenku_spider  
> python 百度文库.py https://wenku.baidu.com/view/9f23f4ecf605cc1755270722192e453611665b54.html
  File "百度文库.py", line 111
    print(text,end='')
                  ^
SyntaxError: invalid syntax
```

**Comment by jk50505k** [comment]
> 1 jigao ~/workspace/wenku_spider > python 百度文库.py File "百度文库.py", line 111 print(text,end='') ^ SyntaxError: invalid syntax 1 jigao ~/workspace/wenku_spider > python 百度文库.py https://wenku.baidu.com/view/9f23f4ecf605cc1755270722192e453611665b54.html File "百度文库.py", line 111 print(text,end='') ^ SyntaxError: invalid syntax

python的版本是3.x以上吗

**Comment by JigaoLuo** [comment]
都有  我尝试了`python3`  
```
 %  jigao  ~  
> python --version                                                        4325ms
Python 2.7.15rc1

 %  jigao  ~  
> python3 --version
Python 3.6.7

 %  jigao  ~  
> python3 ~/workspace/wenku_spider/百度文库.py 
Traceback (most recent call last):
  File "/home/jigao/workspace/wenku_spider/百度文库.py", line 3, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

```

**Comment by jk50505k** [comment]
> 都有 我尝试了`python3`
> 
> ```
>  %  jigao  ~  
> > python --version                                                        4325ms
> Python 2.7.15rc1
> 
>  %  jigao  ~  
> > python3 --version
> Python 3.6.7
> 
>  %  jigao  ~  
> > python3 ~/workspace/wenku_spider/百度文库.py 
> Traceback (most recent call last):
>   File "/home/jigao/workspace/wenku_spider/百度文库.py", line 3, in <module>
>     from bs4 import BeautifulSoup
> ModuleNotFoundError: No module named 'bs4'
> ```

给python3的环境安装bs4库 pip install bs4

**Comment by JigaoLuo** [comment]
可以下载 但是下载pdf生成的png很乱 
你可以试一下这`https://wenku.baidu.com/view/9f23f4ecf605cc1755270722192e453611665b54.html`吗？ 效果如何？

**Comment by jk50505k** [comment]
> 可以下载 但是下载pdf生成的png很乱
> 你可以试一下这`https://wenku.baidu.com/view/9f23f4ecf605cc1755270722192e453611665b54.html`吗？ 效果如何？

pdf效果是不好 以后有时间再更新
